[build]
  base = "astore-frontend"
  publish = "astore-frontend/dist" 
  command = "npm install && npm run build"
# in netlify.toml
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
