[build]
  base = "astore-frontend"
  publish = "dist"       # ← change this from astore-frontend/dist to just dist
  command = "npm install && npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
